
all:
	cd hello_1; make
	cd hello_2; make
	cd hello_3; make
	cd hello_4; make
	cd parallel-for/; make
	cd load-balancing/; make
	cd pi/; make
	cd sum/; make

clean:
	cd hello_1; make clean
	cd hello_2; make clean
	cd hello_3; make clean
	cd hello_4; make clean
	cd parallel-for/; make clean
	cd load-balancing/; make clean
	cd pi/; make clean
	cd sum/; make clean

